"""crear tabla aportes_ahorro

Revision ID: 0cd9cb335fe3
Revises: 7354a2dc0191
Create Date: 2026-03-17 15:26:13.977580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd9cb335fe3'
down_revision: Union[str, Sequence[str], None] = '7354a2dc0191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aportes_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas_ahorro.id'], ),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportes_ahorro_id'), 'aportes_ahorro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aportes_ahorro_id'), table_name='aportes_ahorro')
    op.drop_table('aportes_ahorro')
    # ### end Alembic commands ###
