"""crear table pagos_deudas

Revision ID: 3e0843b60d53
Revises: 710863a50d55
Create Date: 2026-03-17 15:09:51.747614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0843b60d53'
down_revision: Union[str, Sequence[str], None] = '710863a50d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('deuda_a_pagar', 'deuda_a_cobrar'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_restante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tasa_interes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('periodicidad_pago', sa.Enum('mensual', 'quincenal', 'semanal'), nullable=True),
    sa.Column('cuota_periodica', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cuenta_id_asociada', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id_asociada'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deudas_id'), 'deudas', ['id'], unique=False)
    op.create_table('pagos_deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deuda_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('intereses_pagados', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saldo_restante_despues', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('transaccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], ),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transacciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_deudas_id'), 'pagos_deudas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_deudas_id'), table_name='pagos_deudas')
    op.drop_table('pagos_deudas')
    op.drop_index(op.f('ix_deudas_id'), table_name='deudas')
    op.drop_table('deudas')
    # ### end Alembic commands ###
