"""crear tabla plantillas_fijas

Revision ID: 710863a50d55
Revises: 3f9e630bfde3
Create Date: 2026-03-17 15:03:28.449305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710863a50d55'
down_revision: Union[str, Sequence[str], None] = '3f9e630bfde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_fijas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'gasto'), nullable=False),
    sa.Column('periodicidad', sa.Enum('mensual', 'quincenal', 'semanal', 'anual'), nullable=False),
    sa.Column('dia_periodo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultima_generacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_fijas_id'), 'plantillas_fijas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plantillas_fijas_id'), table_name='plantillas_fijas')
    op.drop_table('plantillas_fijas')
    # ### end Alembic commands ###
