"""crear tabla metas_ahorro

Revision ID: 7354a2dc0191
Revises: 3e0843b60d53
Create Date: 2026-03-17 15:13:35.971513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7354a2dc0191'
down_revision: Union[str, Sequence[str], None] = '3e0843b60d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metas_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('monto_objetivo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_ahorro_id'), 'metas_ahorro', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metas_ahorro_id'), table_name='metas_ahorro')
    op.drop_table('metas_ahorro')
    # ### end Alembic commands ###
