"""crear tabla cuentas

Revision ID: a17956c5776d
Revises: cfaead1a5bc2
Create Date: 2026-03-17 09:20:33.044594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17956c5776d'
down_revision: Union[str, Sequence[str], None] = 'cfaead1a5bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('efectivo', 'cuenta_corriente', 'ahorro', 'tarjeta_credito', 'inversion'), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('incluir_en_patrimonio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_id'), 'cuentas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuentas_id'), table_name='cuentas')
    op.drop_table('cuentas')
    # ### end Alembic commands ###
