"""crear tabla presupuesto

Revision ID: cabd5e835026
Revises: 0cd9cb335fe3
Create Date: 2026-03-17 15:39:55.005818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabd5e835026'
down_revision: Union[str, Sequence[str], None] = '0cd9cb335fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('monto_limite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'categoria_id', 'mes', 'anio', name='unique_presupuesto_por_mes')
    )
    op.create_index(op.f('ix_presupuestos_id'), 'presupuestos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuestos_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    # ### end Alembic commands ###
